name: Android CI
on: [push, workflow_dispatch]

env:
  QT_VERSION: 5.15.2

jobs:
  build:
    name: Build Vremenar (Android)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: android

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v2-preview
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Configure & prepare
        env:
          MAPS_ENDPOINT: ${{ secrets.MAPS_ENDPOINT }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          APPCAST_ENDPOINT: ${{ secrets.APPCAST_ENDPOINT }}
          COUNTLY_APPKEY: ${{ secrets.COUNTLY_APPKEY }}
          COUNTLY_APPKEY_DEV: ${{ secrets.COUNTLY_APPKEY_DEV }}
          COUNTLY_ENDPOINT: ${{ secrets.COUNTLY_ENDPOINT }}
          COUNTLY_SALT: ${{ secrets.COUNTLY_SALT }}
          COUNTLY_SALT_DEV: ${{ secrets.COUNTLY_SALT_DEV }}
          FIREBASE_CONFIG_DEV: ${{ secrets.FIREBASE_CONFIG_DEV }}
        run: |
          cat <<EOT > source/config.pri
          MAPS_ENDPOINT="${MAPS_ENDPOINT}"
          API_ENDPOINT="${API_ENDPOINT}"
          APPCAST_ENDPOINT="${APPCAST_ENDPOINT}"
          COUNTLY_APPKEY="${COUNTLY_APPKEY}"
          COUNTLY_ENDPOINT="${COUNTLY_ENDPOINT}"
          COUNTLY_SALT="${COUNTLY_SALT}"
          EOT
          echo $FIREBASE_CONFIG_DEV | base64 --decode > source/resources/Android/output/google-services.json
          mkdir build

      - name: Setup dependencies
        run: ./source/scripts/prepare_dependencies.sh android

      - name: Build
        working-directory: build
        env:
          ARTIFACT_NAME: Vremenar_Android_universal.apk
          VREMENAR_PATH: ../source
          ANDROID_NDK_PLATFORM: android-21
        run: |
          export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle
          qmake $VREMENAR_PATH/Vremenar.pro -spec android-clang CONFIG+=release CONFIG+=qtquickcompiler ANDROID_ABIS="armeabi-v7a arm64-v8a x86 x86_64"
          make -j2
          make apk
          # mv android-build/build/outputs/apk/debug/android-build-debug.apk $ARTIFACT_NAME
