name: iOS CI (Qt5)
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "**"
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/actions/**"
      - ".github/workflows/CI-Android.yml"
      - ".github/workflows/CI-iOS.yml"
      - ".github/workflows/CI-Linux.yml"
      - ".github/workflows/CI-macOS.yml"
      - ".github/workflows/CI-Windows-Qt5.yml"
      - ".github/workflows/CI-Windows.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 5.15.2
  MAPLIBRE_VERSION: 2.0.1

jobs:
  build:
    name: Build Vremenar (iOS / macOS 12 x64)
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==2.1.*
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Download MapLibre
        run: |
          wget https://github.com/maplibre/qt-geoservices-maplibre-gl/releases/download/v${MAPLIBRE_VERSION}/qt-geoservices-maplibre-gl_v${MAPLIBRE_VERSION}_Qt${QT_VERSION}_iOS.tar.bz2
          tar xvf qt-geoservices-maplibre-gl_v${MAPLIBRE_VERSION}_Qt${QT_VERSION}_iOS.tar.bz2 -C ..

      - name: Setup Fastlane
        working-directory: source
        run: |
          bundle install

      - name: Setup deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}

      - name: Setup dependencies
        run: |
          brew install ldid
          ./source/3rdparty/Firebase/iOS/download.sh
          ./source/3rdparty/Countly/iOS/download.sh

      - name: Configure & prepare
        env:
          MAPS_ENDPOINT: ${{ secrets.MAPS_ENDPOINT }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          APPCAST_ENDPOINT: ${{ secrets.APPCAST_ENDPOINT }}
          COUNTLY_APPKEY: ${{ secrets.COUNTLY_APPKEY }}
          COUNTLY_APPKEY_DEV: ${{ secrets.COUNTLY_APPKEY_DEV }}
          COUNTLY_ENDPOINT: ${{ secrets.COUNTLY_ENDPOINT }}
          COUNTLY_SALT: ${{ secrets.COUNTLY_SALT }}
          COUNTLY_SALT_DEV: ${{ secrets.COUNTLY_SALT_DEV }}
        run: |
          cat <<EOT > source/config.pri
          MAPS_ENDPOINT="${MAPS_ENDPOINT}"
          API_ENDPOINT="${API_ENDPOINT}"
          APPCAST_ENDPOINT="${APPCAST_ENDPOINT}"
          COUNTLY_APPKEY="${COUNTLY_APPKEY}"
          COUNTLY_ENDPOINT="${COUNTLY_ENDPOINT}"
          COUNTLY_SALT="${COUNTLY_SALT}"
          EOT

      - name: Build
        working-directory: source
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle exec fastlane ios testbuild || bundle exec fastlane ios testbuild
