name: Continuous Integration
on: [push]

env:
  QT_VERSION: 5.14.2

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: "Linux Ubuntu 16.04 x64"
            artifact: "Vremenar-x86_64.AppImage"
            os: ubuntu-16.04
            platform: linux
            target: desktop
          - name: "Android Universal"
            artifact: "Vremenar_Android_universal.apk"
            os: ubuntu-latest
            platform: android
            target: android
          - name: "macOS Latest x64"
            artifact: "Vremenar_macOS.dmg"
            os: macos-latest
            platform: macos
            target: desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: ${{ matrix.config.target }}

      - name: Set up JDK 1.8
        if: matrix.config.platform == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure & prepare
        run: |
          sed -e 's/MAPS_ENDPOINT_VALUE/$$(MAPS_ENDPOINT)/g' \
            -e 's/ARSO_API_ENDPOINT_VALUE/$$(ARSO_API_ENDPOINT)/g' \
            -e 's/ARSO_API_RESOURCES_VALUE/$$(ARSO_API_RESOURCES)/g' \
            -e 's/COUNTLY_APPKEY_VALUE/$$(COUNTLY_APPKEY_DEV)/g' \
            -e 's/COUNTLY_ENDPOINT_VALUE/$$(COUNTLY_ENDPOINT)/g' \
            -e 's/COUNTLY_SALT_VALUE/$$(COUNTLY_SALT)/g' \
            config.pri.example > config.pri
          cd ..
          mkdir build

      - name: Setup dependencies
        env:
          PLATFORM: ${{ matrix.config.platform }}
        run: ./prepare_dependencies.sh ${PLATFORM}

      - name: Build (macOS)
        if: matrix.config.platform == 'macos'
        working-directory: ../build
        env:
          ARTIFACT_NAME: ${{ matrix.config.artifact }}
          VREMENAR_PATH: ../Vremenar
          MAPS_ENDPOINT: ${{ secrets.MAPS_ENDPOINT }}
          ARSO_API_ENDPOINT: ${{ secrets.ARSO_API_ENDPOINT }}
          ARSO_API_RESOURCES: ${{ secrets.ARSO_API_RESOURCES }}
        run: |
          qmake $VREMENAR_PATH/Vremenar.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
          make -j2
          macdeployqt Vremenar.app -qmldir=$VREMENAR_PATH/src/qml/ -dmg
          mv Vremenar.dmg $ARTIFACT_NAME

      - name: Build (Linux)
        if: matrix.config.platform == 'linux'
        working-directory: ../build
        env:
          ARTIFACT_NAME: ${{ matrix.config.artifact }}
          VREMENAR_PATH: ../Vremenar
          MAPS_ENDPOINT: ${{ secrets.MAPS_ENDPOINT }}
          ARSO_API_ENDPOINT: ${{ secrets.ARSO_API_ENDPOINT }}
          ARSO_API_RESOURCES: ${{ secrets.ARSO_API_RESOURCES }}
        run: |
          # Install gcc 8
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install libgl-dev libxkbcommon-x11-dev gcc-8 g++-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
          # Build
          qmake $VREMENAR_PATH/Vremenar.pro -spec linux-g++ CONFIG+=qtquickcompiler
          make -j2
          make INSTALL_ROOT=appdir -j2 install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage"
          chmod a+x linuxdeployqt-6-x86_64.AppImage
          ./linuxdeployqt-6-x86_64.AppImage appdir/usr/share/applications/vremenar.desktop \
            -qmldir=$VREMENAR_PATH/src/qml/ \
            -extra-plugins=geoservices/libqtgeoservices_mapboxgl.so,geoservices/libqtgeoservices_osm.so,sqldrivers/libqsqlite.so \
            -appimage
          mv Vremenar--x86_64.AppImage $ARTIFACT_NAME

      - name: Build (Android)
        if: matrix.config.platform == 'android'
        working-directory: ../build
        env:
          ARTIFACT_NAME: ${{ matrix.config.artifact }}
          VREMENAR_PATH: ../Vremenar
          ANDROID_NDK_PLATFORM: android-21
          MAPS_ENDPOINT: ${{ secrets.MAPS_ENDPOINT }}
          ARSO_API_ENDPOINT: ${{ secrets.ARSO_API_ENDPOINT }}
          ARSO_API_RESOURCES: ${{ secrets.ARSO_API_RESOURCES }}
        run: |
          export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle
          qmake $VREMENAR_PATH/Vremenar.pro -spec android-clang CONFIG+=qtquickcompiler ANDROID_ABIS="armeabi-v7a arm64-v8a x86 x86_64"
          make -j2
          make apk
          mv android-build/build/outputs/apk/debug/android-build-debug.apk $ARTIFACT_NAME

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config.artifact }}
          path: ../build/${{ matrix.config.artifact }}
